version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6
    container_name: nebulanft-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nebulanft

  # Backend API
  backend:
    build: ./server
    container_name: nebulanft-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/nebulanft?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRE: 7d
      UPLOAD_PATH: ./uploads
      MAX_FILE_SIZE: 10485760
      FRONTEND_URL: http://localhost:3000
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend
  frontend:
    build: ./client
    container_name: nebulanft-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api

volumes:
  mongodb_data: